apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shim.fullname" . }}
  labels:
    {{- include "shim.labels" . | nindent 4 }}
data:
  conf.yaml: |
    reader:
      type: generic
      generic:
        rulerBaseURL: {{ .Values.conf.rulerBaseURL }}
        querierBaseURL: {{ .Values.conf.querierBaseURL }}
    writer:
      type: configmap
      {{- if .Values.conf.configmap.enabeld }}
      configmap:
        namespace: {{ .Values.conf.configmap.namespace }}
        name: {{ .Values.conf.configmap.name }}
        key: {{ .Values.conf.configmap.key }}
      {{- end }}
